options:
  service_params:
    default: 'fake param'
    description: Some parameters to pass to the service
    type: string
  generic_param:
    default: 'generic'
    description: Dummy parameter
    type: string